### ISSUE TITLE
Major version number bump causing confusion and nuget dependency resolution problems

### ISSUE THREAD

**Issue by coderjoe** [cincuranet/log4net-nuget#5]
log4net-nuget was major version number bumped to 2.0.0 when the new strong name key was released. This has started to cause our organization headaches when used with packages which auto-package using the old nuget package version numbering scheme as dependencies.

The most obvious problem are old packages which depend on log4net >= 1.2.13 which nuget happily fulfills with 2.0.0 but which is actually 1.2.11.

It is fair to say that people writing nuget packages with dependencies on log4net from nuget should get their versions right, but this particular version bump forces manual intervention after nuget dependency resolution in order to create a successful build.

I've also left bug reports on those packages which use the wrong version number and suggested that they avoid on a specific log4net nuget package (since there are multiple packages with differing version numbers and package version schemes).

It would avoid a lot of confusion if the package and assembly version numbers could stay in sync. What are the chances  this package could go back to being bundled with a nuget package version which mirrors the assembly version?

**Comment by cincuranet** [comment]
We had that before, but that caused even more harm. :\ Change in signing keys, deprecating the old, without changing major version was IMO not the best move from log4net.

**Comment by coderjoe** [comment]
You're not wrong, but we've traded one problem for another. Since the only problem package in my current project hitting this problem is Common.Logging.Log4Net I'll see if I can continue to bug them to update their package dependencies to be more accurate. It looks like most other packages have started using your version scheme so I'll close this issue.

Sucks that this happened, but then again strong binding in .net just kind of sucks in an open-source ecosystem. Thanks for all your hard work!
