### ISSUE TITLE
CLI 1.0 Compatible assembly

### ISSUE THREAD

**Issue by kerryjiang** [cincuranet/log4net-nuget#6]
Hello sir, which target framework's assembly should I pick if I want to use an CLI 1.0 Compatible assembly which can keep binary compatibility with Mono?

It is said we'd better use the CLI 1.0 Compatible assembly.
http://logging.apache.org/log4net/release/framework-support.html

**Comment by cincuranet** [comment]
You should ask [here](http://logging.apache.org/log4net/mail-lists.html).
